services:
  mysql:
    image: mysql:8.0
    ports:
      - ${DOCKER_MYSQL_PORT:-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=testuser
      - MYSQL_DATABASE=meekrodb

  waitmysql:
    image: mysql:8.0
    links:
      - mysql
    depends_on:
      - mysql
    entrypoint:
      - bash
      - -c
      - 'until /usr/bin/mysql -hmysql -utestuser -ppass -e "SELECT 1"; do sleep 5; done'

volumes:
  mysql_data:
    driver: local
